#!/bin/bash
set -x 
cd $OPENSHIFT_DATA_DIR
nohup java -jar craftbukkit-dev.jar -h $OPENSHIFT_CRAFTBUKKIT_IP -p $OPENSHIFT_CRAFTBUKKIT_PORT_TCP --noconsole > $OPENSHIFT_CRAFTBUKKIT_LOG_DIR/server.log 2>&1 &
